    - name: install jdk
      yum: 
        name: "{{ item }}"
        state: present
      loop:
        - java-11-openjdk
        - java-17-openjdk
        - java-21-openjdk

    - name: start tomcat service
      systemd:
           name: tomcat
           state: started
           enabled: yes
      
 
