    - name: install jdk
      yum: 
        name: "{{ item }}"
        state: present
      loop:
        - java-11-openjdk
        - java-17-openjdk
        - java-21-openjdk



    - name: creating a directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755
        
    - name: downloading tomcat
      unarchive:
       src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.102/bin/apache-tomcat-9.0.102.tar.gz
       dest: /opt/tomcat
       remote_src: yes
       extra_opts: [--strip-components=1]

    - name: creating tomcat service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Tomcat service
          After=network.target
          [Service]
          Type=forking
          Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.20.1.1-2.el9.x86_64"
          Environment="CATALINA_BASE=/opt/tomcat"
          Environment="CATALINA_HOME=/opt/tomcat"
          Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          [Install]
          WantedBy=multi-user.target
    - name: reload daemon
      systemd:  
         daemon_reload: yes
    - name: start tomcat service
      systemd:
           name: tomcat
           state: started
           enabled: yes
      
 
